import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/Shared/Header'
import styles from '../styles/Home.module.css'
import HeroSlider from '../components/LandingPage/HeroSlider'
import CardSlider from '../components/LandingPage/CardSlider'

export default function Home() {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      {/* <HeroSlider/> */}
      <CardSlider></CardSlider>
      <CardSlider/>
      <CardSlider/>
      
    </div>
  )
}
